### ISSUE TITLE
Evaluation on my own data

### ISSUE THREAD

**Issue by ahaemhumright** [AndreeaDogaru/SphereGuided#4]
Hi，
Thank you for the great work.
I am trying to test your model on my own dataset (which share the same structure with NeRF-synthetic dataset). 
However, directly testing result are bad and did not converge. In the Readme file, it says that "...we preprocess each scene to fit into the bounding sphere of radius one...". 
I 'm wondering if it is necessary to rescale the scene as pre-processing? If it is, could you share your pre-processing code?
Thank you.

**Comment by AndreeaDogaru** [comment]
Hello,

Thank you for your interest in our work!
Indeed, the codebase assumes that the scenes are centered at the origin and scaled so that the region of interest is a bounded unit sphere. 
For the NeRF-synthetic dataset, we used the ground truth meshes to compute the translation and the scale factor required to normalize the scene. Alternatively, you could use an SfM point cloud, as exemplified in the [NeuS repo](https://github.com/Totoro97/NeuS/tree/main/preprocess_custom_data#option-2-use-colmap).
